CREATE TABLE mkt.properties (
  property_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  property_name VARCHAR(255) NOT NULL UNIQUE,
  is_competitor BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
